# Generated by Django 4.2.6 on 2023-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=10)),
                ('totalreviews', models.IntegerField()),
                ('password', models.CharField(default='password', max_length=225)),
                ('email', models.CharField(default='email', max_length=225)),
                ('fname', models.CharField(default='fName', max_length=225)),
                ('lname', models.CharField(default='lName', max_length=225)),
            ],
        ),
    ]
