# Generated by Django 4.2.6 on 2024-02-07 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
