# Generated by Django 4.2.6 on 2024-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review_policeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pw', max_length=225),
        ),
    ]
