# Generated by Django 4.2.6 on 2024-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewType',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
