# Generated by Django 4.2.6 on 2024-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_review_reviewtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='feelRating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.CharField(max_length=1500),
        ),
    ]
