# Generated by Django 4.2.6 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_review_feelrating_alter_review_reviewtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
