# Generated by Django 4.2.6 on 2024-02-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='userID',
        ),
    ]
