# Generated by Django 4.2.6 on 2024-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_review_latitude_remove_review_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
