# Generated by Django 4.2.6 on 2024-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_review_feelrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anon',
            field=models.BooleanField(default=False),
        ),
    ]
