# Generated by Django 4.2.6 on 2023-11-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=255)),
                ('countryRating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('gradientID', models.AutoField(primary_key=True, serialize=False)),
                ('gradientName', models.CharField(max_length=50)),
                ('HEX', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceDivision',
            fields=[
                ('policeID', models.AutoField(primary_key=True, serialize=False)),
                ('policeName', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('crimeRating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('crimeType', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_records', to='areas.city')),
                ('policeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_records', to='areas.policedivision')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='countryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='areas.country'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaID', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('avgFeelRating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='areas.city')),
                ('gradientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='areas.gradient')),
                ('policeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='areas.policedivision')),
            ],
        ),
    ]
