# Generated by Django 4.2.6 on 2024-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policedivision',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=50),
        ),
        migrations.AlterField(
            model_name='policedivision',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=50),
        ),
    ]
